### ISSUE TITLE
Bug: Error when connecting Infinitton Board

### ISSUE THREAD

**Issue by daniel3p4u** [bitfocus/companion#121]
A JavaScript error occurs when connecting the infinitton board via USB. ISE Software is not running!

OS: windows 10 64bit
Version: Companion v1.1.0

This is the content of the message:

Uncaught Exception:
Error: could not send feature report to device
    at Infinitton.fillColor (C:\Users\danie\AppData\Local\Programs\companion\resources\app.asar\node_modules\infinitton-idisplay\index.js:189:15)
    at Infinitton.clearKey (C:\Users\danie\AppData\Local\Programs\companion\resources\app.asar\node_modules\infinitton-idisplay\index.js:233:15)
    at new infinitton (C:\Users\danie\AppData\Local\Programs\companion\resources\app.asar\lib\infinitton.js:62:19)
    at elgatoDM.addDevice (C:\Users\danie\AppData\Local\Programs\companion\resources\app.asar\lib\elgato_dm.js:95:27)
    at C:\Users\danie\AppData\Local\Programs\companion\resources\app.asar\lib\elgato_dm.js:71:10
    at elgatoDM.refreshDevices (C:\Users\danie\AppData\Local\Programs\companion\resources\app.asar\lib\elgato_dm.js:74:5)
    at Socket.<anonymous> (C:\Users\danie\AppData\Local\Programs\companion\resources\app.asar\lib\elgato_dm.js:35:10)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at C:\Users\danie\AppData\Local\Programs\companion\resources\app.asar\node_modules\socket.io\lib\socket.js:528:12

**Comment by haakonnessjoen** [comment]
So nothing happends with the infinitton right? Seems like a bug in the node-hid module (or underlying usb driver). The Infinitton needs to be sent a feature report for each button to write to, unlike the Stream Deck. So this is probably only a problem with Infinitton and not Streamdeck.

I tried a quick google search after node-hid, windows and "could not send feature report to device", but didn't find much. So I am unsure if we can do anything about this.

But I have had success with Windows 7 and the Infinitton (in an virtualbox). Maybe someone else could confirm that Infinitton does or does not work in Windows 10, or if this is a freak accident with your setup.

**Comment by skermanator** [comment]
I am also getting the same error. 
Windows 10 Pro
Companion-v1.1.0

**Comment by alpha-io** [comment]
No Error shown with v1.3.0 on Windows 10 Pro, but also no detection and function of the Infinitton.
On OSX 10.14.2 no Problems.

**Comment by haakonnessjoen** [comment]
@alpha-io Could you check your device manager, and see if you find the infinitton device, and in that case, what vendorId and productId it has?

**Comment by alpha-io** [comment]
@haakonnessjoen 
VendorID:  ffff
ProductID:   1f40

Latest build 94c21f9-1305 is detecting the Infinitton but not showing in the Connected devices list.

**Comment by josephdadams** [comment]
@daniel3p4u @skermanator @alpha-io are you guys still having problems with your infinniton devices when using a 2.0 version of Companion?

**Comment by josephdadams** [comment]
Closing due to inactivity from requesters.
