### ISSUE TITLE
[BUG] companion-module-bitfocus-companion Crash on import

### ISSUE THREAD

**Issue by MeestorX** [bitfocus/companion#1631]
**Describe the bug**

Crash following import of a page.

```
lib/page Set page 3 to  { name: 'PAGE' } +27m
  lib/db db_set(page, [object Object]) +27m
  lib/graphics page controls invalidated for page 3 +27m
  lib/device updateControls() IS OBSOLETE, AND SHOULD BE FIXED +27m
/Users/andyb/Dropbox/Documents/companion/companion/node_modules/companion-module-bitfocus-companion/index.js:388
        for (var i = 0; i < self.devices.length; ++i) {
                                         ^

TypeError: Cannot read property 'length' of undefined
    at instance.init_actions (/Users/andyb/Dropbox/Documents/companion/companion/node_modules/companion-module-bitfocus-companion/index.js:388:35)
    at instance.pages_update (/Users/andyb/Dropbox/Documents/companion/companion/node_modules/companion-module-bitfocus-companion/index.js:164:7)
    at EventEmitter.emit (events.js:326:22)
    at EventEmitter.<anonymous> (/Users/andyb/Dropbox/Documents/companion/companion/lib/page.js:55:10)
    at EventEmitter.emit (events.js:314:20)
    at Socket.<anonymous> (/Users/andyb/Dropbox/Documents/companion/companion/lib/loadsave.js:366:13)
    at Socket.emit (events.js:314:20)
    at Socket.emitUntyped (/Users/andyb/Dropbox/Documents/companion/companion/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/andyb/Dropbox/Documents/companion/companion/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
**To Reproduce**

Import a page

**Expected behavior**
Imports properly

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: MacOS 10.15.7
- Browser: Safari
- Companion Version: Today's build

**Additional context**

**Comment by Julusian** [comment]
Already fixed by https://github.com/bitfocus/companion/commit/9398bff7787db6e7401420098d6307d7558ee251
