### ISSUE TITLE
[BUG] Docker container crashes occasionally

### ISSUE THREAD

**Issue by ryanbrink** [bitfocus/companion#1904]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I just migrated our Docker setup from a Windows PC to a Docker container running on a Synology NAS. I imported our configuration and everything seems great. All the buttons work as expected and I haven't noticed any issues and Companion had a few days of uptime.

Today, I started getting notifications that the Docker container crashed. It happened while we weren't using our system at all. Crashed about 3 times within a couple hours. Restarted fine, but I'm not sure what could be going on.

Container output logs look like this:
```
2022-02-11 18:52:04	stdout	Started
2022-02-11 18:51:57	stdout	Starting
2022-02-11 18:27:33	stdout	Started
2022-02-11 18:27:26	stdout	Starting
2022-02-11 18:27:12	stderr	    at processImmediate (internal/timers.js:464:21)
2022-02-11 18:27:12	stderr	    at Immediate.<anonymous> (/root/lib/device.js:116:15)
2022-02-11 18:27:12	stderr	TypeError: Cannot read property 'setConfig' of undefined
2022-02-11 18:27:12	stderr	
2022-02-11 18:27:12	stderr	           ^
2022-02-11 18:27:11	stderr	self.panel.setConfig(config, function (redraw) {
2022-02-11 18:27:09	stderr	/root/lib/device.js:116
2022-02-11 17:30:55	stdout	Started
2022-02-11 17:30:47	stdout	Starting
2022-02-11 17:30:40	stderr	    at processImmediate (internal/timers.js:464:21)
2022-02-11 17:30:40	stderr	    at Immediate.<anonymous> (/root/lib/device.js:116:15)
2022-02-11 17:30:40	stderr	TypeError: Cannot read property 'setConfig' of undefined
2022-02-11 17:30:40	stderr	
2022-02-11 17:30:40	stderr	           ^
2022-02-11 17:30:40	stderr	self.panel.setConfig(config, function (redraw) {
2022-02-11 17:30:40	stderr	/root/lib/device.js:116
2022-02-11 17:30:35	stdout	Started
2022-02-11 17:30:24	stdout	Starting
2022-02-11 17:30:08	stderr	    at processImmediate (internal/timers.js:464:21)
2022-02-11 17:30:08	stderr	    at Immediate.<anonymous> (/root/lib/device.js:116:15)
2022-02-11 17:30:08	stderr	TypeError: Cannot read property 'setConfig' of undefined
2022-02-11 17:30:08	stderr	
2022-02-11 17:30:08	stderr	           ^
2022-02-11 17:30:08	stderr	self.panel.setConfig(config, function (redraw) {
2022-02-11 17:30:07	stderr	/root/lib/device.js:116
2022-02-07 13:57:46	stdout	Started
2022-02-07 13:57:42	stdout	Starting
2022-02-07 13:55:24	stdout	Started
2022-02-07 13:55:17	stdout	Starting
```

### Steps To Reproduce

It seems to be crashing the container somewhat sporadically, but it is happening with no activity from any satellites. 

### Expected Behavior

No crashing

### Environment (please complete the following information)

```markdown
- OS: Docker
- Browser: N/A
- Companion Version: 2.2.0 (2.2.0-d31855c01)
```

### Additional context

Here is the configuration export:
[HarvestSynology_full-config_20220211-1901.companionconfig.json.txt](https://github.com/bitfocus/companion/files/8051024/HarvestSynology_full-config_20220211-1901.companionconfig.json.txt)

**Comment by Julusian** [comment]
That error looks like a bug that was fixed a whole ago. Could you make sure you are running the latest docker image and try again?

**Comment by ryanbrink** [comment]
Thanks for getting back so quick! I created the container from this image last week:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/5272967/153657418-1f930be4-2be0-4f03-97ab-331e1262f02c.png">

Is there some way I can validate I have the right version? I noticed the latest tagged release of Companion on Github is 2.1.4, and the version listed in my browser is 2.2.0-d31855c01, so I believe this is a very current version?

**Comment by Julusian** [comment]
I think you have a ~19 day old beta build, which is new enough.
The errors that are logged look like they could be trying to change the brightness of a surface that doesnt support it?
as for the other restarts, I dont know why that would be happening

**Comment by ryanbrink** [comment]
Okay, thanks. It looks like the only restart cycles I've seen in the logs are directly following that error–so hopefully that helps!

We had an event yesterday and everything was rock-solid. So I may hold off a bit and see if it crashes anymore and then try the update. Thanks!
