### ISSUE TITLE
Bug in the mute function of the Behringer X-Air module

### ISSUE THREAD

**Issue by sskrede** [bitfocus/companion#212]
**Describe the bug**
A bug in the Mute / Unmute channel function on the Behringer xair - module

When a button is created with the mute function, in this example muting ch 1, the application reports the following error message:

"
Uncaught Exception:
Error: The specified packet was not recognized as a valid OSC message or bundle. Packet was: {
  "address": "null01/mix/on",
  "args": [
    {
      "type": "i",
      "value": null
    }
  ]
}
    at Object.osc.writePacket (/Applications/Companion.app/Contents/Resources/app.asar/node_modules/osc/src/osc.js:937:19)
    at osc.UDPPort.p.encodeOSC (/Applications/Companion.app/Contents/Resources/app.asar/node_modules/osc/src/osc-transports.js:68:27)
    at osc.UDPPort.p.send (/Applications/Companion.app/Contents/Resources/app.asar/node_modules/osc/src/osc-transports.js:54:28)
    at EventEmitter.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/lib/osc.js:49:17)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at instance.action (/Applications/Companion.app/Contents/Resources/app.asar/lib/module/xair/index.js:503:15)
    at EventEmitter.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/lib/instance.js:158:33)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
 "

**To Reproduce**

1. Add XR-mixer
2. Assign button to mute a channel
3. Press the button
4. Go get coffee (optional)
5. See error message

**Expected behavior**
Expected profit.

**Screenshots**
<img width="420" alt="companion-error" src="https://user-images.githubusercontent.com/41839051/44675251-41916580-aa30-11e8-9a16-dec6c7e213d1.png">

**Desktop (please complete the following information):**
 - OS X 10.13.6
 - Safari
 - 26.08.2018 build

**Additional context**

**Comment by sskrede** [comment]
Also a similar bug in the "Set fader level" functio:

"Uncaught Exception:
Error: The specified packet was not recognized as a valid OSC message or bundle. Packet was: {
  "address": "null01/mix/fader",
  "args": [
    {
      "type": "f",
      "value": null
    }
  ]
}
    at Object.osc.writePacket (/Applications/Companion.app/Contents/Resources/app.asar/node_modules/osc/src/osc.js:937:19)
    at osc.UDPPort.p.encodeOSC (/Applications/Companion.app/Contents/Resources/app.asar/node_modules/osc/src/osc-transports.js:68:27)
    at osc.UDPPort.p.send (/Applications/Companion.app/Contents/Resources/app.asar/node_modules/osc/src/osc-transports.js:54:28)
    at EventEmitter.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/lib/osc.js:49:17)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at instance.action (/Applications/Companion.app/Contents/Resources/app.asar/lib/module/xair/index.js:503:15)
    at EventEmitter.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/lib/instance.js:158:33)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
"

**Comment by PerRoine** [comment]
You have to set the Type as well as the channel or else this fault will happen, I will make a default selection for those dropdowns so that it's impossible to not have a selection in Type

**Comment by PerRoine** [comment]
Have added default for the dropdowns and removed the need to add leading 0 in channel numbers, this should stop the osc sender from receiving illegal osc values. I have not tested on actual HW but I looked at the OSC strings and they look propper. Closing for now, reopen if there should be further problems I also added DCA control to the X32
