### ISSUE TITLE
Dockerfile fails to build

### ISSUE THREAD

**Issue by llamafilm** [bitfocus/companion#2542]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For testing a module, I tried to build a docker image from the [Dockerfile](https://github.com/bitfocus/companion/blob/master/Dockerfile) in this repo.  It failed with this output:

```
% docker build . 
[+] Building 205.5s (15/21)                                                                       docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 1.89kB                                                                            0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 259B                                                                                 0.0s
 => [internal] load metadata for docker.io/library/debian:bullseye-slim                                           1.6s
 => [internal] load metadata for docker.io/library/node:18-bullseye                                               1.7s
 => [companion-builder 1/8] FROM docker.io/library/node:18-bullseye@sha256:7268327f2e3391b4c67337d55b2cd575f5e1  19.5s
 => => resolve docker.io/library/node:18-bullseye@sha256:7268327f2e3391b4c67337d55b2cd575f5e1ddc16ed2048a02e24ba  0.0s
 => => sha256:7268327f2e3391b4c67337d55b2cd575f5e1ddc16ed2048a02e24ba4b1e03e8a 1.21kB / 1.21kB                    0.0s
 => => sha256:f99109a2ce3267f04c49aebfead6ff6e52a8aef5dee9394aafe4c5b1a0207b8f 2.00kB / 2.00kB                    0.0s
 => => sha256:f6b93d8a5b83f98a79c669807fe20f03f0dce8688ecfe410021873577afa2211 7.25kB / 7.25kB                    0.0s
 => => sha256:c0f6f6b31000e991bdd81caebc21e281fc1350f09586d393f3b8bf36dceeb99e 15.75MB / 15.75MB                  4.3s
 => => sha256:49185a1a3bc353699370ac57d50a7b7234b59616b6aebde79ba6a0a0314bb107 53.70MB / 53.70MB                  2.7s
 => => sha256:385ee361272e1c36fe7d96fe8ab6b0f30cf33bfb9bbe29bfc2d33f51bd771993 54.68MB / 54.68MB                 11.5s
 => => extracting sha256:49185a1a3bc353699370ac57d50a7b7234b59616b6aebde79ba6a0a0314bb107                         2.1s
 => => sha256:69a603957da8fb844ffa8e86445842d8c1a4ab087651d93eb89e98d27562de9e 189.78MB / 189.78MB               12.3s
 => => sha256:dd8c7644888acd5c625e5ecdd8f447831964e2e5f148dbb075e25e337a74690e 4.21kB / 4.21kB                    4.6s
 => => sha256:5ff2883a76705aa63aaf1591b1e67f5644bfb4e452d0d237ef6bb0e438a0ae93 45.86MB / 45.86MB                 12.6s
 => => extracting sha256:c0f6f6b31000e991bdd81caebc21e281fc1350f09586d393f3b8bf36dceeb99e                         0.4s
 => => extracting sha256:385ee361272e1c36fe7d96fe8ab6b0f30cf33bfb9bbe29bfc2d33f51bd771993                         1.6s
 => => sha256:8ac28d90f84f782307a0f55e33b343c29cc343231cb982c27383bebec53a3588 2.28MB / 2.28MB                   12.3s
 => => sha256:a25fe24e849a50ef5ff68deec7c799137bb16e3a3e553ef2fec2ddb44f87e54f 450B / 450B                       12.4s
 => => extracting sha256:69a603957da8fb844ffa8e86445842d8c1a4ab087651d93eb89e98d27562de9e                         4.7s
 => => extracting sha256:dd8c7644888acd5c625e5ecdd8f447831964e2e5f148dbb075e25e337a74690e                         0.0s
 => => extracting sha256:5ff2883a76705aa63aaf1591b1e67f5644bfb4e452d0d237ef6bb0e438a0ae93                         1.4s
 => => extracting sha256:8ac28d90f84f782307a0f55e33b343c29cc343231cb982c27383bebec53a3588                         0.0s
 => => extracting sha256:a25fe24e849a50ef5ff68deec7c799137bb16e3a3e553ef2fec2ddb44f87e54f                         0.0s
 => [stage-1 1/8] FROM docker.io/library/debian:bullseye-slim@sha256:fd3b382990294beb46aa7549edb9f40b11a070f959  14.7s
 => => resolve docker.io/library/debian:bullseye-slim@sha256:fd3b382990294beb46aa7549edb9f40b11a070f959365ef7f31  0.0s
 => => sha256:73a0914422727a2c9dd4f5515b660079248561794cbc7a551443562ae0bd4ba0 529B / 529B                        0.0s
 => => sha256:f6309ca446a2b4b03b58d300c6a9e3b7810363b221cd71a34ed34fefe0c8694f 1.48kB / 1.48kB                    0.0s
 => => sha256:fd3b382990294beb46aa7549edb9f40b11a070f959365ef7f316724b2e425f90 1.85kB / 1.85kB                    0.0s
 => => sha256:795b5d192ab1819e75375fead3f2f931bd86046e3308224944f16a5ec3b97424 30.06MB / 30.06MB                 13.6s
 => => extracting sha256:795b5d192ab1819e75375fead3f2f931bd86046e3308224944f16a5ec3b97424                         1.0s
 => [internal] load build context                                                                                 2.1s
 => => transferring context: 102.37MB                                                                             0.8s
 => [stage-1 2/8] WORKDIR /app                                                                                    1.4s
 => [companion-builder 2/8] RUN apt-get update && apt-get install -y     libusb-1.0-0-dev     libudev-dev     &&  3.2s
 => [companion-builder 3/8] RUN yarn config set network-timeout 200000 -g                                         0.4s
 => [companion-builder 4/8] WORKDIR /app                                                                          0.0s
 => [companion-builder 5/8] COPY . /app/                                                                          0.3s
 => [companion-builder 6/8] RUN CI=1 ./tools/yarn.sh                                                            139.5s
 => [companion-builder 7/8] RUN yarn build:writefile                                                              0.9s
 => ERROR [companion-builder 8/8] RUN ELECTRON=0 yarn dist                                                       39.8s
------
 > [companion-builder 8/8] RUN ELECTRON=0 yarn dist:
0.217 yarn run v1.22.19
0.389 $ zx ./tools/build/complete.mjs
0.565 $ zx tools/build/dist.mjs 
0.741 $ zx tools/build_writefile.mjs
0.906 Writing BUILD: 3.0.0+6049-master-126f27e8
0.907 Writing SENTRY: 
0.959 $ yarn webpack
1.249 $ /app/node_modules/.bin/webpack
39.30 assets by status 8.84 MiB [cached] 8 assets
39.30 orphan modules 6.71 MiB [orphan] 821 modules
39.30 runtime modules 4.4 KiB 12 modules
39.30 modules by path ./node_modules/ 7.38 MiB (javascript) 1.56 KiB (asset)
39.30   javascript modules 7.12 MiB 1234 modules
39.30   json modules 267 KiB 14 modules
39.30   ./node_modules/@companion-module/base/package.json 42 bytes (javascript) 1.56 KiB (asset) [built] [code generated]
39.30 modules by path ./lib/ 6.01 MiB (javascript) 5.27 KiB (asset)
39.30   cacheable modules 5.83 MiB (javascript) 5.27 KiB (asset) 50 modules
39.30   + 4 modules
39.30 modules by path ./*.js 6 KiB (javascript) 5.96 KiB (asset)
39.30   ./main.js 5.96 KiB [built] [code generated]
39.30   ./main.js 42 bytes (javascript) 5.96 KiB (asset) [built] [code generated]
39.30 + 38 modules
39.30 
39.30 WARNING in ./node_modules/express/lib/view.js 81:13-25
39.30 Critical dependency: the request of a dependency is an expression
39.30  @ ./node_modules/express/lib/application.js 22:11-28
39.30  @ ./node_modules/express/lib/express.js 18:12-36
39.30  @ ./node_modules/express/index.js 11:0-41
39.30  @ ./lib/Registry.js 3:0-29 199:24-38
39.30  @ ./main.js 8:0-40 180:22-30
39.30 
39.30 WARNING in ./node_modules/keyv/src/index.js 22:14-40
39.30 Critical dependency: the request of a dependency is an expression
39.30  @ ./node_modules/cacheable-request/dist/index.js 9:0-24 191:42-46 217:36-40 221:29-33 227:29-33
39.30  @ ./node_modules/got/dist/source/core/index.js 7:0-89 840:41-57 989:33-52
39.30  @ ./node_modules/got/dist/source/index.js 14:0-32 14:0-32
39.30  @ ./lib/Cloud/Controller.js
39.30  @ ./lib/Registry.js 5:0-51 214:19-34
39.30  @ ./main.js 8:0-40 180:22-30
39.30 
39.30 2 warnings have detailed information that is not shown.
39.30 Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
39.30 
39.30 ERROR in ./main.js 15:0-56
39.30 Module not found: Error: Can't resolve './launcher/Paths.cjs' in '/app'
39.30 resolve './launcher/Paths.cjs' in '/app'
39.30   using description file: /app/package.json (relative path: .)
39.30     using description file: /app/package.json (relative path: ./launcher/Paths.cjs)
39.30       /app/launcher/Paths.cjs doesn't exist
39.30 
39.30 webpack 5.84.1 compiled with 1 error and 2 warnings in 37201 ms
39.50 error Command failed with exit code 1.
39.50 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
39.54 Error: error Command failed with exit code 1.
39.54     at file:///app/tools/build/dist.mjs:37:8
39.54     exit code: 1
39.56 Error: $ zx tools/build_writefile.mjs
39.56 Writing BUILD: 3.0.0+6049-master-126f27e8
39.56 Writing SENTRY: 
39.56 $ yarn webpack
39.56 $ /app/node_modules/.bin/webpack
39.56 assets by status 8.84 MiB [cached] 8 assets
39.56 orphan modules 6.71 MiB [orphan] 821 modules
39.56 runtime modules 4.4 KiB 12 modules
39.56 modules by path ./node_modules/ 7.38 MiB (javascript) 1.56 KiB (asset)
39.56   javascript modules 7.12 MiB 1234 modules
39.56   json modules 267 KiB 14 modules
39.56   ./node_modules/@companion-module/base/package.json 42 bytes (javascript) 1.56 KiB (asset) [built] [code generated]
39.56 modules by path ./lib/ 6.01 MiB (javascript) 5.27 KiB (asset)
39.56   cacheable modules 5.83 MiB (javascript) 5.27 KiB (asset) 50 modules
39.56   + 4 modules
39.56 modules by path ./*.js 6 KiB (javascript) 5.96 KiB (asset)
39.56   ./main.js 5.96 KiB [built] [code generated]
39.56   ./main.js 42 bytes (javascript) 5.96 KiB (asset) [built] [code generated]
39.56 + 38 modules
39.56 
39.56 WARNING in ./node_modules/express/lib/view.js 81:13-25
39.56 Critical dependency: the request of a dependency is an expression
39.56  @ ./node_modules/express/lib/application.js 22:11-28
39.56  @ ./node_modules/express/lib/express.js 18:12-36
39.56  @ ./node_modules/express/index.js 11:0-41
39.56  @ ./lib/Registry.js 3:0-29 199:24-38
39.56  @ ./main.js 8:0-40 180:22-30
39.56 
39.56 WARNING in ./node_modules/keyv/src/index.js 22:14-40
39.56 Critical dependency: the request of a dependency is an expression
39.56  @ ./node_modules/cacheable-request/dist/index.js 9:0-24 191:42-46 217:36-40 221:29-33 227:29-33
39.56  @ ./node_modules/got/dist/source/core/index.js 7:0-89 840:41-57 989:33-52
39.56  @ ./node_modules/got/dist/source/index.js 14:0-32 14:0-32
39.56  @ ./lib/Cloud/Controller.js
39.56  @ ./lib/Registry.js 5:0-51 214:19-34
39.56  @ ./main.js 8:0-40 180:22-30
39.56 
39.56 2 warnings have detailed information that is not shown.
39.56 Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
39.56 
39.56 ERROR in ./main.js 15:0-56
39.56 Module not found: Error: Can't resolve './launcher/Paths.cjs' in '/app'
39.56 resolve './launcher/Paths.cjs' in '/app'
39.56   using description file: /app/package.json (relative path: .)
39.56     using description file: /app/package.json (relative path: ./launcher/Paths.cjs)
39.56       /app/launcher/Paths.cjs doesn't exist
39.56 
39.56 webpack 5.84.1 compiled with 1 error and 2 warnings in 37201 ms
39.56 error Command failed with exit code 1.
39.56 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
39.56 Error: error Command failed with exit code 1.
39.56     at file:///app/tools/build/dist.mjs:37:8
39.56     exit code: 1
39.56     at file:///app/tools/build/complete.mjs:3:8
39.56     exit code: 1
39.61 error Command failed with exit code 1.
39.62 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:21
--------------------
  19 |     
  20 |     # build the application
  21 | >>> RUN ELECTRON=0 yarn dist
  22 |     
  23 |     # make the production image
--------------------
ERROR: failed to solve: process "/bin/sh -c ELECTRON=0 yarn dist" did not complete successfully: exit code: 1
```

### Expected Behavior

Docker image should build successfully

### Environment (please complete the following information)

```markdown
- OS: MacOS 13.0
- Docker 24.0.2
- Companion Version: 126f27e
```

**Comment by Julusian** [comment]
Thanks for reporting this, we stopped using this docker file for the official builds, because cross-building the arm64 image was timing out, so we arent verifying this hasnt been broken anywhere...

This is fixed in beta and the stable-3.0 (will become 3.0.1 at some point)

**Comment by llamafilm** [comment]
Thanks, the build works for me now, using beta branch.
But I'm unable to add a module for testing because `yarn` is apparently missing.  Is there a better way to do this?  Essentially, I'm trying to verify that my module can run properly on a fresh container, without any dependencies from my dev environment.

```
% docker run -it --name companion -p 8000:8000 -v ./:/app/module-local-dev:ro 3ce22fd31ada
Installing dependencies for all local dev modules...
Installing dependencies for module companion-module-crestron-digitalmatrix
/docker-entrypoint.sh: line 14: yarn: command not found
```

**Comment by Julusian** [comment]
ok, I've taken a look at this, and I think this is working now in beta
