### ISSUE TITLE
[BUG] Companion 3.99 Experimental doesn't launch on a brand new machine

### ISSUE THREAD

**Issue by peternewman** [bitfocus/companion#2557]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Companion fails to launch due to errors trying to update its (non-existent) internal database.

Found whilst testing a new release of #2436

### Steps To Reproduce

1. Open Companion on a new computer (or having renamed/deleted C:\Users\<username>\AppData\Roaming\companion)
2. Companion fails to launch

### Expected Behavior

Companion launches and generates an empty database.

### Environment (please complete the following information)

```markdown
- OS: Windows 10
- Browser: N/A
- Companion Version: companion-win64-3.99.0+6257-develop-abf9c43e
```

### Additional context

Console log:
```
Sentry DSN not located
Sentry error reporting is disabled
2023-08-24T22:44:58.152Z Application: Companion process started
2023-08-24T22:45:01.814Z info Log/Controller Application starting
2023-08-24T22:45:01.824Z info Registry Build 3.99.0+6257-develop-abf9c43e
2023-08-24T22:45:01.827Z info Registry configuration directory: C:\Users\user\AppData\Roaming\companion\v3.99
2023-08-24T22:45:01.957Z info Data/Upgrade Upgrading db from version 2 to 4
Startup failed: TypeError: Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at m (D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:2755842)
    at Object.y [as upgradeStartup] (D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:2756094)
    at p (D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:2749367)
    at new c (D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:2728359)
    at k.ready (D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:2937781)
    at f.<anonymous> (D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:3051988)
    at f._actionHandler (D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:2542748)
    at D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:2551081
    at f._chainOrCall (D:\Temp\companion-win64-3.99.0+6257-develop-abf9c43e\$PLUGINSDIR\app-64\resources\main.js:2:2549721)
2023-08-24T22:45:02.112Z Application: Restart Count: 1
2023-08-24T22:45:06.368Z info Log/Controller Application starting
```

C:\Users\<username>\AppData\Roaming\companion\v3.99\db.v2 contents
`{"page_config_version":3}`

**Comment by peternewman** [comment]
Thanks @Julusian .

Would it be worth some basic unit type tests to confirm loading an empty file works (and maybe also upgrading from previous versions)?

**Comment by Julusian** [comment]
yeah we should really start adding some more unit tests, so adding one for this specific case would be good

**Comment by peternewman** [comment]
I've made an initial attempt at this in #2588 but as mentioned in there it doesn't currently run via Jest properly, I don't know if you've any ideas...
