### ISSUE TITLE
[BUG] Unable to start beta in dev mode

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion#2608]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting this error after updating to the latest beta commit 5527ba5, when using yarn dev to run companion

I'm not seeing this in the builds from the site, or when switching to the dev branch

```
TypeError: Cannot read properties of undefined (reading 'pageNumber') TypeError: Cannot read properties of undefined (reading 'pageNumber')
    at CloudController.getBanks (file:///Users/bryce/Documents/GitHub/companion/lib/Cloud/Controller.js:195:21)
    at CloudController.updateAllBanks (file:///Users/bryce/Documents/GitHub/companion/lib/Cloud/Controller.js:639:21)
    at new CloudController (file:///Users/bryce/Documents/GitHub/companion/lib/Cloud/Controller.js:149:8)
    at Registry.ready (file:///Users/bryce/Documents/GitHub/companion/lib/Registry.js:222:16)
    at Command.<anonymous> (file:///Users/bryce/Documents/GitHub/companion/main.js:184:4)
    at Command.listener [as _actionHandler] (/Users/bryce/Documents/GitHub/companion/node_modules/commander/lib/command.js:482:17)
    at /Users/bryce/Documents/GitHub/companion/node_modules/commander/lib/command.js:1300:65
    at Command._chainOrCall (/Users/bryce/Documents/GitHub/companion/node_modules/commander/lib/command.js:1197:12)
    at Command._parseCommand (/Users/bryce/Documents/GitHub/companion/node_modules/commander/lib/command.js:1300:27)
    at /Users/bryce/Documents/GitHub/companion/node_modules/commander/lib/command.js:1081:27
```

**Comment by Julusian** [comment]
Hopefully a3e60b3cb952d522a6e98198e4293ed30cac4629 is better?
I can't explain why it hit that, other than your db has some lost controls which sounds bad..

There have been too many issues like this recently.. Some bad merge conflicts between beta and develop causing types to no longer line up..

**Comment by bryce-seifert** [comment]
Works great! Thanks as always for the help. I figured it was just something errant in my setup, but wanted to flag it in case it was a problem for others too.
