### ISSUE TITLE
[BUG] Missing Font after update from 3.1.3 to 3.2.0 on RPi

### ISSUE THREAD

**Issue by koensayr** [bitfocus/companion#2716]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After running the companion-update script the companion process won't start and complains about a missing font:

```
shirhadash@CompanionPi:/var/log $ /opt/companion/node-runtime/bin/node /opt/companion/main.js --extra-module-path /opt/companion-module-dev
2024-01-25T04:46:26.187Z info Log/Controller Application starting 
2024-01-25T04:46:26.199Z info Registry Build 3.2.0+6663-stable-b83f412f 
2024-01-25T04:46:26.201Z info Registry configuration directory: /home/shirhadash/.config/companion-nodejs/v3.2 
2024-01-25T04:46:26.344Z info Data/Upgrade Upgrading db from version 3 to 4 
2024-01-25T04:46:26.375Z info Log/Controller Sentry error reporting configured 
2024-01-25T04:46:26.387Z info Graphics/Controller Render worker created 
2024-01-25T04:46:26.396Z info Graphics/Controller Render worker created 
Startup failed: Error: No such file or directory (os error 2): "assets/Fonts/Arimo-Regular.ttf" Error: No such file or directory (os error 2): "assets/Fonts/Arimo-Regular.ttf"
    at FontLibrary.use (/opt/companion/node_modules/@julusian/skia-canvas/lib/index.js:824:31)
    at new D (/opt/companion/main.js:2:2772825)
    at B.ready (/opt/companion/main.js:2:2918971)
    at f.<anonymous> (/opt/companion/main.js:2:3048758)
    at f._actionHandler (/opt/companion/main.js:2:2503229)
    at /opt/companion/main.js:2:2511654
    at f._chainOrCall (/opt/companion/main.js:2:2510271)
    at f._parseCommand (/opt/companion/main.js:2:2511629)
    at /opt/companion/main.js:2:2509084
    at f._chainOrCall (/opt/companion/main.js:2:2510271)
```

### Steps To Reproduce

Update from the last 3.1.2 experimental build to 3.2.0 using the companion-update script and start companion from the CLI. The following error will be displayed:

Startup failed: Error: No such file or directory (os error 2): "assets/Fonts/Arimo-Regular.ttf" Error: No such file or directory (os error 2): "assets/Fonts/Arimo-Regular.ttf"

### Expected Behavior

Companion Starts Up Normally.

### Environment (please complete the following information)

```markdown
- OS: RPi
- Browser: Safari/Chrome
- Companion Version: 3.2.0
```

**Comment by Julusian** [comment]
I am curious as to why you are running it manually, it works fine when run through the systemd service.

The bug is that it is loading the fonts relative to the working directory, rather than relative to the executable causing it to not find it as you are executing it from somewhere else. I'll get this fixed in the betas and ready for a patch release.
A workaround is to cd to `/opt/companion` before running your command.

**Comment by koensayr** [comment]
> I am curious as to why you are running it manually, it works fine when run through the systemd service.

I was trying to diagnose some connectivity issues with the Streamdeck (turned out to be a cable issue) so wanted logs in the foreground.

Thank you for the fix
