### ISSUE TITLE
Module Request: Decimator Designs UCP Control

### ISSUE THREAD

**Issue by aaronkothe** [bitfocus/companion#458]
**Describe the feature**
Decimator Designs manufactures a variety of converters, splitters, and multi-viewers for video production. Their products are widely regarded as some of the most capable and reliable in the industry.

Most of Decimator's products are controlled by a single, simple (at least for the user) software program, called UCP (current version 2.0.11). Plug in one of their products via USB, 'scan' for hardware, and the options for your Decimator device are displayed.

It would be amazing if Companion could enable Streamdeck to control the UCP software!

**Is this platform dependent (windows, mac, ..)?**
I don't believe so - the software is available for Mac & Windows.

**If documentation is required to implement, do you know where to find it?**
Unfortunately, I know next to nothing about coding, so I don't know what might be helpful for the devs. Here's the link to the download page for UCP: http://decimator.com/DOWNLOADS/DOWNLOADS.html

**Usecases**
The specific use case I envision is with a multi-viewer. Decimator's DMON-QUAD allows customizable presets for multi-view layouts, i.e. having three video inputs displayed one way with another input displayed a different way. The ability to live-switch between these presets using the Streamdeck would be immensely powerful, basically making a super advanced feature only available on very expensive (five figures plus) replicable with something like a basic BMD ATEM, a computer, and a Streamdeck.

This is far from the only use case, though. Decimator makes their products very configurable, so control commands could be created to do all sorts of things depending on the product.

Thank you guys for all you do!

**Comment by Keksstar** [comment]
Helpful would be a control protocol - but sadly there isn´t one in the decimators (except TSL for Tally Stuff - but that´s on the Companion list for ages now...).
So, sadly the commands had to be reverse engineered.

**Comment by hadphild** [comment]
Have you tried to contact decimator about this? They might get UCP with and API if there is a demand for it.

**Comment by aaronkothe** [comment]
I certainly have not tried to contact Decimator. Am I the right person to do that?

**Comment by JeffreyDavidsz** [comment]
Well you're the one asking for the support. Keep in mind that all work on companion is done in spare time of the programmer's. If they/we need to search up all API's or contact all manufacturer's because there's a request on GitHub.... So yeah feel free to contact them and ask for the protocol. Happy to implement it for you

**Comment by Keksstar** [comment]
Good luck with this one.... I never got an direct answer from Decimator when asking things. Only from their distributor Symbiosis - which wasn´t helpfull. But give it a try! :-)

**Comment by hadphild** [comment]
Hi Phil,
 
Currently there is no API for our products.
 
Best Regards,
Edward Wright
DECIMATOR DESIGN
Phone: +61 (0)2 4577-8725
Any opinions expressed in this

**Comment by Keksstar** [comment]
Uhm.... which mail address did you used to contact them?

**Comment by hadphild** [comment]
tech@decimator.com

**Comment by aaronkothe** [comment]
@JeffreyDavidsz Got it! I'm happy to contact them, I just didn't want to overstep my bounds. I definitely respect the dev team's time!

**Comment by DeeJayMX** [comment]
There is the UMD TSL Protocol in the Decimator DMON but it's just triggering the Tally boxes and the UMD name...

It's a RS485 connection obviously

**Comment by Keksstar** [comment]
THAT‘s why #120 is still open. That‘s the point where it‘s needed for. But no one cares... 👎
I‘m using another Software for TSL now

**Comment by DeeJayMX** [comment]
But It can be a really change over if we can change PIP source of DMON device, or recall Multiview Layout.

But there is a really reverse enginering to do for the Decimator...

poor situation that there is no API from Decimator...

**Comment by aaronkothe** [comment]
<img width="1045" alt="screen shot 2019-02-07 at 10 21 35 pm" src="https://user-images.githubusercontent.com/46914512/52458728-c677c380-2b26-11e9-8acf-971f69549763.png">

**Comment by aaronkothe** [comment]
So it seems that Decimator isn't going to be of much help at the moment, unfortunately. Is it possible to reverse engineer their control protocol, etc.? Is this something I could pay someone to work on? Or is it not recommended since the manufacturer doesn't seem intent on supporting it? Or shall I just give it a rest? Haha

**Comment by quentinmit** [comment]
I'm working on trying to reverse-engineer the protocol. Unfortunately it looks like they're using an FTDI serial converter chip... in bit-banging mode! No simple ASCII protocols here. I can understand why they don't want to publish documentation. (BTW, their GUI app is written in Delphi Pascal!)

I've actually managed to reverse engineer enough now to read the version number from my MD-HX. You have to write a magic string and then it clocks out 512 bytes of data. Bytes 0-1 are the string "GW" (maybe the config's magic?) then bytes 2-5 are the version number (0x00 0x01 0x00 0x04 in my case, for version 1.4) and then it's followed by packed binary data.

Before I go on to trying to decode the data, I want to figure out what low-level protocol they're speaking. It's almost but not quite I2C - it's some kind of 2 wire synchronous serial protocol.

**Comment by DeeJayMX** [comment]
Good Work !
Please continue !

**Comment by aaronkothe** [comment]
@quentinmit brother I have no idea what 90% of that means but I am stoked that you are working on it. Please keep at it.

**Comment by JeffreyDavidsz** [comment]
@quentinmit TSL protocol?

**Comment by DeeJayMX** [comment]
Something can be done with TSL but not everything like changing sources for example

**Comment by quentinmit** [comment]
@JeffreyDavidsz I only have an MD-HX so TSL is not an option for me. (Sounds like it's only available on the DMON?)

**Comment by aaronkothe** [comment]
I have MD-HX, MD-LX, and DMON-QUAD. Please let me know if there is a way I can help.

**Comment by quentinmit** [comment]
I've made some great progress reverse engineering the protocol. I can now reliably switch inputs on my MD-HX and read the current state:

```
bash-3.2$ python3 decimctl.py
[(b'DECIMATOR DESIGN', b'MD-HX', b'CLA42882')]
b'GW\x00\x01\x00\x06\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x03\x85\x06\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\xff\x05\x00\x00\x00\x00\x00 \xff\x00\x01\x00\x00\xff\x01\x01\x00\x00\x05\xff\x00\x07\xff\x102\x102Tv\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfft\xe9\x87\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
struct CPA_Registers {
    magic [c_ubyte_Array_2] = [71, 87];
    version_major [c_ushort_be] = 1;
    version_minor [c_ushort_be] = 6;
    unknown06 [c_ubyte_Array_10] = [255, 255, 255, 255, 255, 255, 255, 255, 255, 255];
    unknown10 [c_ubyte_Array_16] = [0, 3, 133, 6, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255];
    unknown20 [c_ubyte_Array_2] = [0, 255];
    DUCFormat [c_ubyte] = 5;
    unknown23 [c_ubyte_Array_8] = [0, 0, 0, 0, 0, 32, 255, 0];
    Loop_Enable [c_ubyte] = 1;
    unknown2c [c_ubyte_Array_4] = [0, 0, 255, 1];
    HO_Type [c_ubyte] = 1;
    SO_Source [c_ubyte] = 0;
    HO_Source [c_ubyte] = 0;
    unknownDUC [c_ubyte] = 0;
    DUC_Ref [DUC_Ref] = <DUC_Ref.SDI_IN: 2>;
    DUC_Source [DUC_Source] = <DUC_Source.HDMI_IN: 1>;
    unknown34 [c_ubyte] = 255;
    LCDOffTime [LCDOffTime] = <LCDOffTime.OFF_5s: 0>;
};
```

Let me try to package this up a bit and I can have you test it on your MD-LX and DMON-QUAD. One of the things I haven't figured out yet is how the official software distinguishes between the different models.

**Comment by DeeJayMX** [comment]
Damn !!!! You are the guy !

**Comment by DeeJayMX** [comment]
I have DMON 12S and DMON Quad if you need testing !

**Comment by quentinmit** [comment]
Okay, I've posted my WIP:
https://github.com/quentinmit/decimctl

It only really supports the MD-* series right now. After you've installed it, you should be able to run commands like:

```
bash-3.2$ decimctl list
Model: b'MD-HX' Serial: b'CLA42882'
bash-3.2$ decimctl status --serial=CLA42882
struct CPA_Registers {
    magic [c_char_Array_2] = b'GW';
    version_major [c_ushort_be] = 1;
    version_minor [c_ushort_be] = 6;
<snip>
bash-3.2$ decimctl set SO_Source HDMI_IN
bash-3.2$ 
```

I *believe* this should work on Mac, Windows, and Linux. If you could test it on your MD-* devices I would appreciate it. For the DMON devices, can you run the "decimctl list" and "decimctl registers" commands and paste the output here?

I really know nothing about how to integrate this with Bitfocus Companion. I'm hoping someone else on this issue can figure out how to do that.

**Comment by DeeJayMX** [comment]
I can test it on windows today but how ?
Do I need a python console ?

**Comment by quentinmit** [comment]
@DeeJayMX It requires a recent version of Python 3 (maybe 3.6+), pylibftdi, and libftdi. For the former, I think the official package is fine if you don't have it - https://www.python.org/downloads/windows/ For the latter two, see https://pylibftdi.readthedocs.io/en/0.15.0/installation.html#installation

Sorry, I don't really know much about Python on Windows.

**Comment by haakonnessjoen** [comment]
Quick question: Can you distinguish the Decimator device from a random FTDI device, by reading manufacturer/model from ftdi library? Or is the FTDI chip in it just a normal un-altered ftdi chip?

**Comment by quentinmit** [comment]
@haakonnessjoen They program a different VID/PID into it, so yes, they're distinguishable and the normal FTDI drivers won't try to claim the device. (Amusingly, they appear to use the same VID/PID for all their devices.)

**Comment by quentinmit** [comment]
@DeeJayMX @aaronkothe Any luck testing this? I'm specifically looking for the output of `decimctl list` and `decimctl registers` on non-MD-HX devices.

**Comment by quentinmit** [comment]
@aaronkothe Okay, I put together a binary distribution that should run on macOS Mojave (and if we're lucky maybe High Sierra). It includes Python and all the libraries you need.

https://drive.google.com/file/d/1df2M54pLd0o2Yslmldh4MxG2Blfu3Ynx/view?usp=sharing

I'm not sure what your technical level is, but I'll try to walk you through it. Download the zip file and double-click on it to extract it. Open the resulting folder and navigate to `bin` -> `decimctl` inside the folder. Open Apple's Terminal.app (in `/Applications/Utilities/`) and drag + drop the file called `decimctl` onto the new terminal window.

The Terminal window should show something like `~ aaron$ /Users/aaron/Downloads/decimctl-venv/bin/decimctl`. Make sure the Terminal window is focused, and press enter. You should see the help message for `decimctl`. Press the up arrow and the path to `decimctl` should again show in the prompt. Type space and `list` and press enter again. That should print the list of Decimator devices on your system. Then repeat again with `registers` instead of `list`. If you have an MD-* you can try repeating yet again with `set SO_Source HDMI_IN`.

**Comment by haakonnessjoen** [comment]
So, the biggest issue with this, is how hard it will be to get libftdi to compile/link on all supported OS'es in the companion build environment. I should try to do a cross compile with the current build environment for companion, to check if this is even feasible to make a module for. If it does not work, maybe we could do a two part solution though. A python based executable that gives companion access to the devices via some simple protocol.

**Comment by quentinmit** [comment]
@haakonnessjoen Yeah, I was afraid of that. Is there any precedent for doing the latter? It would be somewhat annoying for the user, but you could just have the module shell out to the Python code if it's installed (and leave it up to the user to install the code and its dependencies). Obviously the best would be if you could port (the useful bits of) the code I wrote to JS, but then you'd need to figure out how to link libftdi.

**Comment by aaronkothe** [comment]
I will be attempting to test this tonight with my MD-HX and DMON-Quad

**Comment by quentinmit** [comment]
@aaronkothe Any luck?

**Comment by aaronkothe** [comment]
Working on it right now!

**Comment by aaronkothe** [comment]
I updated the firmware on all devices before running this.

Here is what resulted from running "list" then "registers" then "set SO_Source HDMI_IN" then "status" when **BOTH** an MD-HX and DMON-QUAD were connected at the same time: https://pastebin.com/nmaJKE24

Results when **ONLY** DMON-QUAD was connected: https://pastebin.com/eRNEcQch

Results when **ONLY** MDHX was connected: https://pastebin.com/hhDrHEt6

I have two MD-HX's in my possession at the moment - would it be of any benefit to run on both devices?

Thank you!!

**Comment by aaronkothe** [comment]
Also, I should have an MD-LX available to test in a few days. I'll post when that's done.

**Comment by quentinmit** [comment]
@aaronkothe Thanks! It definitely looks like it successfully talked to your MD-HX and was able to control the SDI Out setting on it. Now that I know the DMON-QUAD is a VFA and I have the register map, I will start working on supporting it. You said the thing you're most interested in controlling is switching between pre-defined custom layouts, right?

**Comment by DeeJayMX** [comment]
And Sources switching please
And name of the windows

**Comment by aaronkothe** [comment]
Awesome! I'm glad I could help. Yes, switching between pre-defined custom layouts via a Companion action would be a dream. Bonus points if you can make switching sources (i.e. change input 1 from being mapped to input 1 to being mapped to input 2) possible as an action. And yes, as @DeeJayMX mentioned, we would need the names or at least input numbers of the inputs to be part of the information Companion receives.

**Comment by DeeJayMX** [comment]
To set the UMD of each windows.
And if possibly, changing color of border...

**Comment by quentinmit** [comment]
@aaronkothe Here's a new build for OS X: https://drive.google.com/open?id=1Va5QsCtMIhyzBYsb1JaDJ05UoEH7djVQ

It should now recognize the DMON-QUAD and allow you to change the layout, UMD, and border colors (maybe?). I don't have a DMON-QUAD to test it on, unfortunately. Try commands like `path/to/decimctl set MVLayout 3` or `path/to/decimctl set BorderColour 3` (or other numbers; it looks like custom layouts start at number 8, for instance).

I sure hope it works because it's going to be mighty hard to debug without having one of them in my hands.

**Comment by haakonnessjoen** [comment]
@aaronkothe instead of writing `/Users/aaronkothe/Downloads/decimctl-venv/bin/decimctl  path/to/decimctl set MVLayout 3` you should try /Users/aaronkothe/Downloads/decimctl-venv/bin/decimctl set MVLayout 3`

**Comment by aaronkothe** [comment]
@haakonnessjoen thanks. I do believe I tried that. See lines 140 and 151 in the paste.

**Comment by aaronkothe** [comment]
@quentinmit forgive me if this is silly, but looking at the results, I do notice that at the beginning of this test, when I'm giving the list, registers, and status commands, the file path referenced is /Users/aaronkothe/Downloads/**decimctl-venv-2**/bin/decimctl

However, at line 137, when I start to enter the new commands, set layout, etc., the file path referenced is /Users/aaronkothe/Downloads/**decimctl-venv**/bin/decimctl

Could it be that I accidentally directed it back to the first build, hence why it isn't working?

**Comment by quentinmit** [comment]
@aaronkothe Yep, I think that's exactly what happened, you ran it with the older version that doesn't know how to control DMON devices.

**Comment by aaronkothe** [comment]
That's weird, I'm not sure how that happened. I used the same process as last time, pressing up arrow then space then the command. Any ideas why it would revert back to the old file path seemingly randomly?

Anyway, I will test again this afternoon and will make sure the file path is correct.

**Comment by aaronkothe** [comment]
@quentinmit here's what I got: https://pastebin.com/aH2aZZBu

Please let me know what else I can do to help.

**Comment by aaronkothe** [comment]
It works! I have control of the DMON-QUAD through the terminal.

I will work on testing functionality and setting various parameters. I have already noticed that when you attempt to set the multiviewer layout to layout 1, it sets it to layout 2, and 2 to 3, and 3 to 4, and so on. I will have some time to explore tonight and let you know what I find.

This is awesome!

**Comment by DeeJayMX** [comment]
This is awesome !!!!!
@quentinmit you're a genius !!!

**Comment by aaronkothe** [comment]
Hey guys. I've done some testing with the second build, and made a list of what parameters can be controlled currently. Almost all of the things on this list have been tested successfully, unless otherwise stated.

https://pastebin.com/5HEuybTM

I did notice that there doesn't seem to be a way to change the Window Input Source, or perhaps I just missed it. This would be a useful feature to have going forward, if possible.

I'll be testing on an MD-LX later today.

So here's my noob question for the day - how do we go from where we are now to this being incorporated in Companion?

**Comment by DeeJayMX** [comment]
I'm not really a dev. but I understand a bit of thing in it.

Do you think it's possible to build an executable or a python AIO build, and receive OSC command through IP (TCP/UDP Stack things...)

I think I have a library somewhere to receive and send OSC command in Python.

Do you think you could do that ?

**Comment by quentinmit** [comment]
I think editing layouts requires a different protocol. (You have to hit the Write button in UCP before it takes effect, right?) I don't think I can safely try implementing that protocol without having a DMON to play with, sorry.

That said, it looks like the Routing tab might be separate. The next time I make a new build I'll include video source settings that look like they'll work for that.

Yes, it would be quite easy to connect this up to OSC. Maybe I'll play with that - can Companion speak OSC?

**Comment by DeeJayMX** [comment]
Yes you're right.
For modifying Layout you have to "write",
But for changing of layout, name, source, it's direct.
No write needed.

Companion speak generic HTTP and Generic OSC, only in a "unicast way" : you can't have feedback in that type of command.
To have the feedback and everything you have to develop an instance, like a plugin that it will be loaded with comanion.
I tried to do one for a special application and it was too complicated for me:

Companion is written in Javascript and uses the node.js runtime.

you can have a look here if you are into:
https://github.com/bitfocus/companion/wiki/Module-Development

**Comment by aaronkothe** [comment]
@quentinmit honestly, I don't think anyone would want to edit layouts via Companion anyway. Or at the very least, that's a feature to be added down the road.

Even just the most recent build you've done would be awesome to have as a Companion instance!

**Comment by DeeJayMX** [comment]
+1

**Comment by quentinmit** [comment]
@DeeJayMX I looked into OSC a bit and it doesn't seem like a great fit - it doesn't provide any way for clients to enumerate the available controls or find out what the valid values for a control are.

**Comment by haakonnessjoen** [comment]
I want us to either try to port it to js for companion. At least check how hard it would be to get ftdi to compile on all platforms (optimal route). Or that we would just make a simple protocol for this usecase, to talk to your application. It could be a simple tcp line based protocol with just JSON data in each direction for commands and data.

**Comment by quentinmit** [comment]
@haakonnessjoen Are there any generic protocols other than OSC that might be a bit more expressive? I'd rather not design something bespoke if we don't have to.

**Comment by aaronkothe** [comment]
Any progress on this fellas?

**Comment by quentinmit** [comment]
@aaronkothe I'm not sure what else I can be doing here; I reverse engineered the protocol and have working code. About the only thing I could work on is support for more products from Decimator Designs, but that's hard without having them accessible to me.

**Comment by aaronkothe** [comment]
@quentinmit no worries man! I'm not trying to pressure anyone, just checking on the progress

**Comment by DeeJayMX** [comment]
Hi @quentinmit 
I'm at the studio right now and can make some test...
What do you want me to do ? I'm downloading python right now ...

**Comment by DeeJayMX** [comment]
Ok I tried everything to install libusb libtfdi with Zadig etc...
But it's not working:

I got this error:

`c:\py\decimctl-master\bin>python` decimctl list
Traceback (most recent call last):
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pylibftdi\driver.py", line 116, in _load_library
    lib = getattr(cdll, dll)
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 426, in __getattr__
    dll = self._dlltype(name)
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Le module spécifié est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "decimctl", line 116, in <module>
    main()
  File "decimctl", line 113, in main
    args.func(args)
  File "decimctl", line 11, in list_devices
    devices = decimctl.list_devices()
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\decimctl-0.2-py3.7.egg\decimctl\__init__.py", line 44, in list_devices
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pylibftdi\driver.py", line 211, in list_devices
    if self.fdll.ftdi_init(byref(ctx)) != 0:
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pylibftdi\driver.py", line 159, in fdll
    self._fdll = self._load_library('libftdi')
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pylibftdi\driver.py", line 121, in _load_library
    lib = getattr(cdll, lib_path)
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 426, in __getattr__
    dll = self._dlltype(name)
  File "C:\Users\Studio\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Le module spécifié est introuvable``

**Comment by quentinmit** [comment]
@DeeJayMX Did you see pylibftdi's [instructions](https://pylibftdi.readthedocs.io/en/0.15.0/installation.html#windows)?

It sounds like you have pylibftdi installed correctly but you're either missing one of the DLLs (libftdi and libusb) or you have a DLL that doesn't match your Python architecture (32-bit vs 64-bit).

**Comment by DeeJayMX** [comment]
I installed everything...
I gonna make some test tomorrow

**Comment by aaronkothe** [comment]
@haakonnessjoen any ideas on how to move this process along? I'm SUPER new here, so forgive my naivety. Is this the point at which a bounty would be helpful?

**Comment by haakonnessjoen** [comment]
So the first we need to do, is to check how hard it is to get ftdi libs to compile on all supported platforms/operating systems of companion. So I might just do a simle ftdi test later today with the build servers. If this is hard, we need to think about a solution where the driver-part is an external application, and then companion connects to it via network.

**Comment by madscientist159** [comment]
I have an MX-HD here that we're evaluating as part of an SDI pipeline, we use Linux pretty much exclusively so using the Windows application is out of the question.  We need to be able to set the scaler framerate from our internal application stack; I can do the required plumbing if the current script supports controlling the scaler parameters.  (Why Decimator didn't include a 'match input framerate' option is beyond me right now...)

Has enough been reverse engineered at this point to control scaler framerate?  If not, is there anything I can provide that would assist?

Thanks!

**Comment by aaronkothe** [comment]
@madscientist159 I'm 95% certain that the current script does support changing the scaler inputs on the MD-HX but I will happily test again if there's any chance you can move the ball forward on this.

When you say that the Windows application is out of the question, are you referring to Decimator's software?

**Comment by madscientist159** [comment]
@aaronkothe Yes, that's correct.  We have a bunch of existing SDI pipelines that for the most part work well once a compatible signal is made available -- the fun is always in trying to glue in various other devices that don't always provide compatible signals.  Hence the Decimator, and our desire to hook something like your script into our (custom) central pipeline control systems.  A point + click GUI app like the Decimator control is completely useless for this application. :smile:   In a nutshell we need to be able to read the input status (SDI/HDMI), feed that back to our central systems (which I can handle), then set up the scaler in whatever way that central system requests it.  Normally that's matched framerate, but sometimes it'll ask for 1/2 framerate conversion or similar too.

This is a beta test for a 4k pipeline later this year / early next; I'm hoping Decimator won't deviate too far with the upcoming 12G converters.  Did you just snoop the Windows app traffic to reverse engineer the registers or was it significantly more involved than that?  Trying to figure out if enabling the 4k devices when they come out is a reasonable goal.

**Comment by aaronkothe** [comment]
@madscientist159 I didn't do anything, @quentinmit did all the work. I'm code-dumb, I'm just the first guy who requested that Decimator products be added to Companion.

So far, what @quentinmit came up with works well with the MD-HX, DMON-QUAD, and probably the MD-LX. However, we seem to be stuck at getting the working script implemented into Companion. I'm willing to sponsor a bounty on this project if it would move it forward.

**Comment by quentinmit** [comment]
@madscientist159 Yep, you should be able to control scaler framerate with `decimctl`. You might want to write your own script that uses the `decimctl` Python library, since the command line interface is currently designed more for humans than automation.

I have no inside information about how similar or different the 4K converter will be. My guess is that it will be similar since all of Decimator's products use the same fundamental protocol, just with different settings to control. Formats are the most complicated of all the settings because they're not just a 0-n list, they have separate bits for SD vs ED vs HD vs 3G and the frame rate and resolution are then combined in a single value that only makes sense for a given standard. So they're definitely going to have to make changes there to add 4K support.

**Comment by madscientist159** [comment]
@quentinmit Ended up switching to BlackMagic -- not only did it work properly out of the box with auto switching, but the Decimator was doing nasty things to the source audio.  For the small price difference, the BlackMagic box is worth it not to have to mess around with this.

**Comment by aaronkothe** [comment]
@haakonnessjoen Another month has passed. Is there anything I can do to help move this process along?
