### ISSUE TITLE
Missing libusb causes few error messages during ./tools/update.sh but exit status is 0 and no final error is given

### ISSUE THREAD

**Issue by depili** [bitfocus/companion#478]
**Describe the bug**
Running the dev environment installation on a fresh rasbian stretch image. Instructions don't mention libusb. tools/update.sh produces the following output:
```
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.2.1" has incorrect peer dependency "popper.js@^1.14.6".
[4/4] Building fresh packages...
[-/5] ⠂ waiting...
[2/5] ⠂ node-hid
[3/5] ⠂ serialport
[4/5] ⠄ websocket
error /home/pi/src/companion/node_modules/node-hid: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /home/pi/src/companion/node_modules/node-hid
Output:
prebuild-install WARN install No prebuilt binaries found (target=8.12.0 runtime=node arch=arm platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/src/companion/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.node-gyp/8.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.node-gyp/8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.node-gyp/8.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/src/companion/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/src/companion/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
                    ^
compilation terminated.
hidapi.target.mk:101: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
make: Leaving directory '/home/pi/src/companion/node_modules/node-hid/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.79-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/src/companion/node_modules/node-hid





Bitfocus skeleton
yarn install v1.13.0
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.27s.

Module dependencies
lib/module/artnet/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.22s.

lib/module/atem/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.25s.

lib/module/christie-wd/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.21s.

lib/module/dcs/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.21s.

lib/module/eventmaster/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.23s.

lib/module/grandma2/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.18s.

lib/module/matrox-monarch/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.67s.

lib/module/neodarque-stagetimer2/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.22s.

lib/module/nevion-mrp/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.18s.

lib/module/obs-studio/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.23s.

lib/module/renewedvision-propresenter/
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.23s.
```
Throwing an error would be preferable, now the real error gets scrolled off screen and in the end the user just gets a broken install.

**To Reproduce**
1. Install 2018-11-13-raspbian-stretch-lite.img on a sd card
2. sudo apt update && sudo apt upgrade
3. sudo apt install npm git
4. sudo npm install n -g
5. sudo npm install yarn -g
6. sudo n 8.12.0
7. git clone https://github.com/bitfocus/companion
8. cd companion && ./tools/update.sh

**Expected behavior**
A working install or at least an error message and non-zero exit status on the failed install

**Desktop (please complete the following information):**
Rasbian stretch lite

**Comment by depili** [comment]
Installing libgusb-dev resolves the compilation problem and thus should be added to the requirements, at least for debian based systems.

**Comment by jarodwsams** [comment]
In current builds of Raspbian, this issue still exists.
Raspbian Buster Lite (both the original July release and the September 2019 update).
Installing via instructions at [documentation/raspberrypi.md](https://github.com/bitfocus/companion/blob/master/documentation/raspberrypi.md)

![image](https://user-images.githubusercontent.com/22972834/66176192-7ce26880-e622-11e9-93ee-24c6b58fd6a0.png)
