### ISSUE TITLE
Mitti Toggle Play Error

### ISSUE THREAD

**Issue by johnnydanger** [bitfocus/companion#554]
Mitti: Toggle Play throws the following error.  I assume it's a typo somewhere in the code and should be 'bool', but I was unable to find the code or offending 'bol' in the repository.  Thanks!

Uncaught Exception:
TypeError: Cannot read property 'bol' of undefined
    at instance.action (/Applications/Companion.app/Contents/Resources/app.asar/lib/module/mitti/mitti.js:466:18)
    at EventEmitter.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/lib/instance.js:313:33)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at EventEmitter.<anonymous> (/Applications/Companion.app/Contents/Resources/app.asar/lib/action.js:342:19)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at EventEmitter.self.on_elgato_click (/Applications/Companion.app/Contents/Resources/app.asar/lib/device.js:162:12)
    at emitMany (events.js:152:20)
    at EventEmitter.emit (events.js:224:7)

**Comment by chrisrouse** [comment]
I can't reproduce the error. Can you provide more detailed info about your settings? Which specific button are you using? Which version of Companion are you using?

**Comment by johnnydanger** [comment]
Mitti
Version 1.5.1 (385)

Companion
Version 1.3.0 (1a7592b-1203)

I'm using a Stream Deck Mini 6-button and have tried a few different buttons on it.  All throw the same error.

**Comment by chrisrouse** [comment]
If you use the Test Actions button in the browser does it have an error? I'm testing with everything on the same computer using localhost and the latest dev build and everything I've tested works the way it should.

**Comment by johnnydanger** [comment]
Yes the Test Actions button throws the error too.

[https://www.dropbox.com/s/zonsagp2uyxdlzu/ErrorToggle.mov?dl=0](url)

**Comment by johnnydanger** [comment]
Oh, I see!  The GM release 1.3.0 does not appear to have the newest Mitti code in it.  The lib/module/mitti/mitti.js file was updated a month ago and removed "var bol" from the code.  But that version of the lib didn't make it into the newest official release.

**Comment by johnnydanger** [comment]
Confirmed.  Just downloaded the the newest developer release and it's fixed.  Thanks for taking a look, Chris!
