### ISSUE TITLE
[BUG] Development headless builds fail, after creating electron build

### ISSUE THREAD

**Issue by thargy** [bitfocus/companion#989]
**Describe the bug**
After using `yarn build` to build an electron build, running `yarn headless` fails with
```
C:\Source Control\GitHub\companion\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The specified module could not be found.
\\?\C:\Source Control\GitHub\companion\node_modules\node-hid\build\Release\HID.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (C:\Source Control\GitHub\companion\node_modules\bindings\bindings.js:112:48)
    at loadBinding (C:\Source Control\GitHub\companion\node_modules\node-hid\nodehid.js:25:42)
    at Object.showdevices [as devices] (C:\Source Control\GitHub\companion\node_modules\node-hid\nodehid.js:127:5)
    at elgatoDM.refreshDevices (C:\Source Control\GitHub\companion\lib\elgato_dm.js:121:20)
    at new elgatoDM (C:\Source Control\GitHub\companion\lib\elgato_dm.js:97:7)
```

**To Reproduce**
Run `yarn build`
Run `yarn headless`

**Expected behavior**
Running a build should not prevent further development.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Companion Version: 2.0

**Additional context**
Running the build appears to replace the `Release\HID.node` binary with a version for electron.  This seems to be incompatible with the headless/dev version.  Removing the node-hid module and reinstalling using `yarn install` fixes the issue.

**Comment by josephdadams** [comment]
@thargy are you still experiencing this?

**Comment by thargy** [comment]
Hi @josephdadams,

Sorry, I haven't had the development environment installed since late February and have not needed to do any more module development since then, it was, of course, still an issue at the time.

**Comment by Julusian** [comment]
This still happens. Its a hazard of using native libraries in a node project.
The only fix would be to do a reverse run of 'electron-rebuild', but I haven't seen any tools which will do that as it isn't very common.

After doing a `yarn build`, you should either delete your node_modules folder and run a `yarn install` again, or don't use `yarn headless` and instead use `yarn dev`

**Comment by Julusian** [comment]
After a recent round of dependency updates, node and electron will both use the same builds of these dependencies, so this is no longer a problem.
If you do a `yarn windist` from a mac, then you will be in a similar situation as before, but this can be resolved by doing a `yarn electron-rebuild`
